In [2]:
from __future__ import print_function
import torch

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[4.6936e+12, 3.0621e-41, 1.4539e+27],
        [4.5558e-41, 1.4539e+27, 4.5558e-41],
        [1.4540e+27, 4.5558e-41, 1.4540e+27],
        [4.5558e-41, 1.4541e+27, 4.5558e-41],
        [1.4541e+27, 4.5558e-41, 1.4542e+27]])


In [4]:
x = torch.rand(5,3)
x

tensor([[0.4040, 0.0765, 0.8621],
        [0.6358, 0.2924, 0.2227],
        [0.5609, 0.6122, 0.1478],
        [0.1327, 0.3255, 0.8700],
        [0.0038, 0.5020, 0.8904]])

In [5]:
x = torch.zeros(5,3, dtype = torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
x= torch.tensor([5.5, 3])
x

tensor([5.5000, 3.0000])

In [7]:
x = x.new_ones(5,3, dtype = torch.double)
print(x)

x = torch.rand_like(x, dtype = torch.float)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[0.1605, 0.4553, 0.4513],
        [0.9712, 0.8516, 0.1703],
        [0.9582, 0.8563, 0.4014],
        [0.9448, 0.0503, 0.2813],
        [0.1709, 0.6992, 0.7587]])


In [8]:
print(x.size())

torch.Size([5, 3])


In [9]:
## Operations

y = torch.rand(5,3)
print(x+ y)

tensor([[0.4197, 1.0014, 0.8985],
        [1.1977, 1.7048, 0.3386],
        [1.7739, 1.6026, 0.9462],
        [1.0937, 0.4103, 0.3652],
        [0.4477, 0.9601, 1.0750]])


In [10]:
print(torch.add(x,y))

tensor([[0.4197, 1.0014, 0.8985],
        [1.1977, 1.7048, 0.3386],
        [1.7739, 1.6026, 0.9462],
        [1.0937, 0.4103, 0.3652],
        [0.4477, 0.9601, 1.0750]])


In [11]:
result= torch.empty(5,3)
torch.add(x,y, out = result)
print(result)

tensor([[0.4197, 1.0014, 0.8985],
        [1.1977, 1.7048, 0.3386],
        [1.7739, 1.6026, 0.9462],
        [1.0937, 0.4103, 0.3652],
        [0.4477, 0.9601, 1.0750]])


In [13]:
# adding inplace

y.add_(x)
print(y)

tensor([[0.4197, 1.0014, 0.8985],
        [1.1977, 1.7048, 0.3386],
        [1.7739, 1.6026, 0.9462],
        [1.0937, 0.4103, 0.3652],
        [0.4477, 0.9601, 1.0750]])


In [14]:
print(x[:,1])

tensor([0.4553, 0.8516, 0.8563, 0.0503, 0.6992])


In [15]:
# resize /reshape tensor

In [16]:
x= torch.randn(4,4)
y = x.view(16)
z= x.view(-1,8)
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [17]:
x= torch.randn(1)
print(x)
print(x.item())

tensor([1.8541])
1.8540984392166138


In [18]:
## Numpy bride

a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [20]:
b = a.numpy()
print(type(b))

<class 'numpy.ndarray'>


In [21]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [22]:
## convertiong numpyarray in to torch sensor

import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out = a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [23]:
### cuda tensor

In [25]:
if torch.cuda.is_available():
    device = torch.device("cuda")
    y = torch.ones_like(x, device = device)
    x = x.to(device)
    z = x+y
    print(z)
    print(z.t0("cpu", torch.double))
else:
    
    print("Its a CPU sys")

Is a CPU sys
